# top level stuff you probably don't need to touch
highlighter: rouge
#markdown: rdiscount
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://bhikadia.com/
baseurl:
title: Harsh Bhikadia
author: Harsh Bhikadia
description: Personal blog and resume
avatar: profile.jpg
email: harsh@bhikadia.com
github: daadu # username
twitter: 4not7
#linkedin: username
stackoverflow: users/2554745/harsh-bhikadia   #e.g: users/2735833/proton1h1
medium: daadu
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-71475870-2


# needed for travis-ci build
exclude: [vendor]
